# Generated by Django 5.0.2 on 2024-02-11 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Valentine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('is_agreed', models.BooleanField(default=False)),
                ('message', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
