# Generated by Django 5.0.2 on 2024-02-12 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('valentine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valentine',
            name='is_agreed',
        ),
    ]
